/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: SofiaWolfie (https://sketchfab.com/SofiaWolfie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/strawberry-cake-ebea5910dc234c35b525478e7eda6aa3
Title: Strawberry cake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cakeHome/scene.gltf')
  return (
    <group {...props} dispose={null} scale={3.4}>
      <group rotation={[0 , -10 , 0 ]} position={[0, 1.8, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.TextureAtlas_1001} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.TextureAtlas_1001} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.TextureAtlas_1001} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.TextureAtlas_1002} />
      </group>
    </group>
  )
}

useGLTF.preload('/cakeHome/scene.gltf')
