/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: emm (https://sketchfab.com/edemaistre)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-1-maison-alyzee-c01b7abbedfa4e49bd25f14c4b2a756a
Title: Cake #1 - Maison Alyzée
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cakeHome2/scene.gltf')
  return (
    <group {...props} dispose={null} scale={25}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/cakeHome2/scene.gltf')
